image: doctoolchain/doctoolchain:v2.1.0

pages:
  stage: build
  script:
    - export DTC_HEADLESS=true
    - ./dtcw generateSite
    - mkdir public
    - cp -r build/microsite/output/. public/.
  artifacts:
    paths:
      - public/
